# Generated by Django 4.2 on 2025-03-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(verbose_name='시험 날짜')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('attendees', models.PositiveIntegerField(verbose_name='응시 인원')),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('CONFIRMED', '확정')], default='PENDING', max_length=50, verbose_name='상태')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
    ]
